`timescale 1ns/1ps
`define TEST_TIMING
`include "src/register/register_file.v"

`define CHECK_RESULT(out, target) \
  if (out !== target) begin \
    $display( \
        "FAIL: %s, expected %d, got %d (%b)", `"out`", target, out, out); \
    $fatal(1); \
  end

module register_file_tb;
    localparam WIDTH = 8;
    localparam IDX_WIDTH = 2;
    localparam NUM_REGS = 1 << IDX_WIDTH;
    // TODO: compute this delay from analyzing the critical path of the graph
    // generated by yosys. This should be done for all modules.
    localparam DELAY = 29;

    reg clk;
    reg not_we;
    reg[IDX_WIDTH-1:0] rd_idx;
    reg[IDX_WIDTH-1:0] rs0_idx;
    reg[IDX_WIDTH-1:0] rs1_idx;
    reg[WIDTH-1:0] in;
    wire[WIDTH-1:0] out0;
    wire[WIDTH-1:0] out1;

    register_file uut(
        .clk(clk),
        .not_we(not_we),
        .rd_idx(rd_idx),
        .rs0_idx(rs0_idx),
        .rs1_idx(rs1_idx),
        .in(in),
        .out0(out0),
        .out1(out1)
    );

    initial begin
        clk = 1'b0;
        not_we = 1'b0;
        rd_idx = 2'b00;
        rs0_idx = 2'b00;
        in = 12;
        #DELAY
        clk = 1'b1;
        #DELAY
        #0
        `CHECK_RESULT(out0, 12);
        clk = 1'b0;
        not_we = 1'b0;
        rd_idx = 2'b01;
        rs0_idx = 2'b00;
        rs1_idx = 2'b01;
        in = 34;
        #DELAY
        clk = 1'b1;
        #DELAY
        #0
        `CHECK_RESULT(out0, 12);
        `CHECK_RESULT(out1, 34);
        clk = 1'b0;
        not_we = 1'b0;
        rd_idx = 2'b10;
        rs0_idx = 2'b01;
        rs1_idx = 2'b10;
        in = 56;
        #DELAY
        clk = 1'b1;
        #DELAY
        #0
        `CHECK_RESULT(out0, 34);
        `CHECK_RESULT(out1, 56);
        clk = 1'b0;
        not_we = 1'b0;
        rd_idx = 2'b11;
        rs0_idx = 2'b10;
        rs1_idx = 2'b11;
        in = 78;
        #DELAY
        clk = 1'b1;
        #DELAY
        #0
        `CHECK_RESULT(out0, 56);
        `CHECK_RESULT(out1, 78);
        clk = 1'b0;
        not_we = 1'b1;
        rd_idx = 2'b00;
        rs0_idx = 2'b00;
        rs1_idx = 2'b01;
        in = 90;
        #DELAY
        clk = 1'b1;
        #DELAY
        #0
        `CHECK_RESULT(out0, 12);
        `CHECK_RESULT(out1, 34);
        clk = 1'b0;
        not_we = 1'b1;
        rd_idx = 2'b10;
        rs0_idx = 2'b10;
        rs1_idx = 2'b11;
        in = 87;
        #DELAY
        clk = 1'b1;
        #DELAY
        #0
        `CHECK_RESULT(out0, 56);
        `CHECK_RESULT(out1, 78);

        $display("SUCCESS: passed all tests");
        $finish;
    end
endmodule