name: Compiler

on:
  push:
    branches: [ "master" ]
    paths:
      - 'compiler/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'compiler/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./compiler

    steps:
    - uses: actions/checkout@v6
    - name: Build
      run: cargo build --verbose
    - name: Check line length
      run: bash scripts/check-line-length.sh
    - name: Format
      run: cargo fmt --check
    - name: Run tests
      run: cargo test --verbose